// LinkedIn DevOps Scanner - Keyword Configuration
// Single source of truth for all keyword arrays

// DevOps keywords - posts must contain at least one of these
const DEFAULT_DEVOPS_KEYWORDS = [
  "devops",
  "dev ops",
  "sre",
  "devops engineer",
  "azure devops engineer",
  "site reliability",
  "platform engineer",
  "platform engineering",
  "cloud engineer",
  "cloud engineering",
  "cloud architect",
  "cloud developer",
  "cloud devops",
  "cloud infrastructure",
  "cloud operations",
  "cloud ops",
  "aws engineer",
  "azure engineer",
  "gcp engineer",
  "kubernetes",
  "k8s",
  "aks",
  "eks",
  "gke",
  "terraform",
  "ci/cd",
  "infrastructure engineer",
  "release engineer",
];

// Hiring signals - stronger match if present
const DEFAULT_HIRING_SIGNALS = [
  "hiring",
  "we're hiring",
  "we are hiring",
  "open role",
  "open position",
  "open positions",
  "now hiring",
  "looking for",
  "join our team",
  "join us",
  "apply now",
  "apply here",
  "actively hiring",
  "immediate opening",
  "immediate openings",
  "job opening",
  "job openings",
  "vacancy",
  "vacancies",
  "career opportunity",
  "we're recruiting",
  "we are recruiting",
];

// Exclude keywords - posts containing these are filtered out
const DEFAULT_EXCLUDE_KEYWORDS = [
  "bootcamp",
  "boot camp",
  "online course",
  "video course",
  "learning course",
  "udemy course",
  "free course",
  "paid course",
  "devops course",
  "tutorial",
  "certification prep",
  "learn devops",
  "learning path",
  "online class",
  "webinar",
  "workshop",
  "devops training program",
  "training bootcamp",
  "training certification",
  "udemy",
  "coursera",
  "pluralsight",
  "linkedin learning",
  "candidates on the bench"
];

// Invalid keywords - posts with these are marked as "Not valid"
const DEFAULT_INVALID_KEYWORDS = [
  "usc only",
  "only usc",
  "us citizen only",
  "only us citizen",
  "us citizens only",
  "only us citizens",
  "must be usc",
  "must be us citizen",
  "citizenship required",
  "us citizenship required",
  "no visa sponsorship",
  "no sponsorship",
  "no h1b",
  "gc holders only",
  "green card only",
  "only green card",
  "w2 only",
  "w-2 only",
  "only w2",
  "only w-2",
  "no c2c",
  "no corp to corp",
  "not - a - hiring post",
  "not a hiring post",
  "available it consultants",
  "available on bench",
  "don't send resumes",
  "visa: usc",
  "not for bench sales",
];

// Skills to detect and tag separately
const DEFAULT_SKILLS = [
  "docker",
  "kubernetes",
  "k8s",
  "terraform",
  "ansible",
  "jenkins",
  "github actions",
  "gitlab ci",
  "circleci",
  "travis ci",
  "aws",
  "azure",
  "gcp",
  "google cloud",
  "aks",
  "eks",
  "gke",
  "python",
  "bash",
  "shell script",
  "golang",
  "go lang",
  "java",
  "prometheus",
  "grafana",
  "github",
  "gitlab",
  "datadog",
  "splunk",
  "elk",
  "elasticsearch",
  "logstash",
  "kibana",
  "new relic",
  "pagerduty",
  "linux",
  "ubuntu",
  "centos",
  "redhat",
  "helm",
  "argocd",
  "spinnaker",
  "mongodb",
  "postgresql",
  "mysql",
  "redis",
  "cassandra",
  "kafka",
  "rabbitmq",
  "nginx",
  "apache",
  "cloudformation",
  "puppet",
  "chef",
  "saltstack",
  "vault",
  "consul",
  "nomad",
  "rancher",
  "openshift",
  "istio",
  "linkerd",
  "envoy",
];

// Combined defaults object for easy access
const DEFAULT_KEYWORDS = {
  devopsKeywords: DEFAULT_DEVOPS_KEYWORDS,
  hiringSignals: DEFAULT_HIRING_SIGNALS,
  excludeKeywords: DEFAULT_EXCLUDE_KEYWORDS,
  invalidKeywords: DEFAULT_INVALID_KEYWORDS,
  skills: DEFAULT_SKILLS
};
